stacks : list[list[str]]= [[], [], [], [], [], [], [], [], []]
stacks[0].append('F')
stacks[0].append('C')
stacks[0].append('J')
stacks[0].append('P')
stacks[0].append('H')
stacks[0].append('T')
stacks[0].append('W')
stacks[1].append('G')
stacks[1].append('R')
stacks[1].append('V')
stacks[1].append('F')
stacks[1].append('Z')
stacks[1].append('J')
stacks[1].append('B')
stacks[1].append('H')
stacks[2].append('H')
stacks[2].append('P')
stacks[2].append('T')
stacks[2].append('R')
stacks[3].append('Z')
stacks[3].append('S')
stacks[3].append('N')
stacks[3].append('P')
stacks[3].append('H')
stacks[3].append('T')
stacks[4].append('N')
stacks[4].append('V')
stacks[4].append('F')
stacks[4].append('Z')
stacks[4].append('H')
stacks[4].append('J')
stacks[4].append('C')
stacks[4].append('D')
stacks[5].append('P')
stacks[5].append('M')
stacks[5].append('G')
stacks[5].append('F')
stacks[5].append('W')
stacks[5].append('D')
stacks[5].append('Z')
stacks[6].append('M')
stacks[6].append('V')
stacks[6].append('Z')
stacks[6].append('W')
stacks[6].append('S')
stacks[6].append('J')
stacks[6].append('D')
stacks[6].append('P')
stacks[7].append('N')
stacks[7].append('D')
stacks[7].append('S')
stacks[8].append('D')
stacks[8].append('Z')
stacks[8].append('S')
stacks[8].append('F')
stacks[8].append('M')


with open("input1.txt", 'r') as file:
    lines = file.readlines()
    for line in lines:
        ops = line.split(' ')
        for i in range(int(ops[1])):
            val = stacks[int(ops[3])-1].pop()
            stacks[int(ops[5])-1].append(val)

out = ''
for stack in stacks:
    out += stack.pop()

print(out)